export interface FiltersRange {
  locations: string[]
  rating_max: number
  reg_time_days_max: number
  price_max: number
  min_span_min: number
  min_span_max: number
  max_span_min: number
  max_span_max: number
  max_bag_size_mb_min: number
  max_bag_size_mb_max: number
  total_provider_space_min: number
  total_provider_space_max: number
  used_provider_space_max: number
  cpu_number_max: number
  total_ram_min: number
  total_ram_max: number
  benchmark_disk_read_speed_min: number
  benchmark_disk_read_speed_max: number
  benchmark_disk_write_speed_min: number
  benchmark_disk_write_speed_max: number
  speedtest_download_min: number
  speedtest_download_max: number
  speedtest_upload_min: number
  speedtest_upload_max: number
  speedtest_ping_min: number
  speedtest_ping_max: number
}

export interface FiltersData {
  location?: string
  has_free_space?: boolean
  is_send_telemetry?: boolean
  cpu_is_virtual?: boolean
  cpu_name?: string
  country?: string
  isp?: string
  storage_git_hash?: string
  provider_git_hash?: string
  rating_gt?: number
  rating_lt?: number
  reg_time_days_gt?: number
  reg_time_days_lt?: number
  uptime_gt_percent?: number
  uptime_lt_percent?: number
  price_gt?: number
  price_lt?: number
  min_span_gt?: number
  min_span_lt?: number
  max_span_gt?: number
  max_span_lt?: number
  max_bag_size_mb_gt?: number
  max_bag_size_mb_lt?: number
  total_provider_space_gt?: number
  total_provider_space_lt?: number
  used_provider_space_gt?: number
  used_provider_space_lt?: number
  cpu_number_gt?: number
  cpu_number_lt?: number
  total_ram_gt?: number
  total_ram_lt?: number
  usage_ram_percent_gt?: number
  usage_ram_percent_lt?: number
  benchmark_disk_read_speed_gt?: number
  benchmark_disk_read_speed_lt?: number
  benchmark_disk_write_speed_gt?: number
  benchmark_disk_write_speed_lt?: number
  speedtest_download_gt?: number
  speedtest_download_lt?: number
  speedtest_upload_gt?: number
  speedtest_upload_lt?: number
  speedtest_ping_gt?: number
  speedtest_ping_lt?: number
}
